name: Update Portfolio Data

on:
  schedule:
    - cron: "0 0 * * *"   # daily run
  workflow_dispatch:       # manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run pull.py
        run: python pull.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # optional (your PAT)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # auto-provided

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add api/stats.json api/visitors.json api/stats-history.json
          git commit -m "🔄 Update stats & visitors [skip ci]" || echo "No changes"
          git push
